openapi: 3.0.1
   
info:
  title: "Capabilities"
  version: "0.1.3.20190201100000A"
  description: "The SICK Standard Capabilities HTTP/REST profile."
   
servers:
  - url: https://{device}/capabilities
    variables:
      device:
        default: 192.168.0.1
  - url: http://{device}/capabilities
    variables:
      device:
        default: 192.168.0.1
tags:
- name: "Capabilities"
 
paths:
  /profiles:
    get:
      tags:
      - "Capabilities"
      summary: "Get a list of the supported HTTP/REST profiles."
      description: ""
      operationId: "profiles"
      parameters:
      - in: query
        name: id
        description: "Filter the resulting device profile list for the profile ids passed."
        required: false
        schema:
          type: array
          items:
            type: string
      responses:
        200:
          description: "successful operation"
          content:
            application/json:
              schema:
                type: "array"
                items:
                  oneOf:
                    - $ref: '#/components/schemas/Profile'
                    - $ref: '#/components/schemas/OpenApiHttpProfile'
                    - $ref: '#/components/schemas/SickProprietaryHttpProfile'
                  discriminator:
                    propertyName: objectType
        400:
          description: "Could not parse the request. More detailed information which parameters are incorrect, can be found in the contained error message array."
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    errorCode:
                      type: number
                      enum:
                        - value: 1001
                          name: UnknownParameter
                          description: The transmitted parameter is unknown.
                        - value: 1002
                          name: InvalidParameterValue
                          description: The value of the transmitted parameter is invalid.
                    errorMessage:
                      type: string
components:
  schemas:
    Profile:
      type: "object"
      properties:
        id:
          type: "string"
          format: GUID
        name:
          type: "string"
        version:
          type: "string"
          description: "The version string must comply with the SICK Versioning Standard 1.0.1."
        description:
          type: "string"
    SickHttpProfile:
        allOf:
          - $ref: '#/components/schemas/Profile'
          - type: object
            properties:
              serviceLocation:
                type: "string"
                format: uri
              specificationLocation:
                type: "string"
                format: uri
    OpenApiHttpProfile:
        allOf:
          - $ref: '#/components/schemas/SickHttpProfile'
          - type: object
    SickProprietaryHttpProfile:
        allOf:
          - $ref: '#/components/schemas/SickHttpProfile'
          - type: object